version: '3'
services:

#   php:
#     image: php:7-apache
#     volumes:
#       - //d/Docker/php7-apache/html:/var/www/html
#     ports:
#       - 80:80
    wordpress:
        image: wordpress
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=abcABC123
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_TABLE_PREFIX=wp
        volumes: 
            - //d/Docker/Wordpress/html:/var/www/html
        ports:
            - 80:80
    db:
        image: mariadb:latest
        environment:
        - MYSQL_ROOT_PASSWORD=abcABC123
        - MYSQL_DATABASE=lemp_db
        ports:
            - 3306:3306